apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: production
  labels:
    app: sample-app
spec:
  type: LoadBalancer                              # provisions a cloud LB
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: sample-app
  # (Optional) annotations for AWS ALB Ingress Controller:
  # metadata:
  #   annotations:
  #     service.beta.kubernetes.io/aws-load-balancer-type: "external"
  #     service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
